
services:

  coordinator:
    build:
      context: .
      dockerfile: src/coordinator/Dockerfile
    container_name: coordinator
    environment:
      - NB_MAPS=${NB_MAPS:-2}
      - NB_REDUCES=${NB_REDUCES:-2}
      - TEXTS_DIR=/app/texts
      - OUTPUT_DIR=/app/output
    volumes:
      - ./texts:/app/texts
      - ./output:/app/output
    networks:
      - mapreduce-net

  map-worker:
    build:
      context: .
      dockerfile: src/mapworker/Dockerfile
    environment:
      - COORDINATOR_HOST=coordinator
    volumes:
      - ./texts:/app/texts
    networks:
      - mapreduce-net
    depends_on:
      - coordinator

  reduce-worker:
    build:
      context: .
      dockerfile: src/reduceworker/Dockerfile
    environment:
      - COORDINATOR_HOST=coordinator
    networks:
      - mapreduce-net
    depends_on:
      - coordinator

networks:
  mapreduce-net:
    driver: bridge
